# Generated by Django 5.1.15 on 2026-09-24 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_sessions', '0002_focussession_distracted_secs_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='focussession',
            name='goal',
            field=models.CharField(blank=True, choices=[('STUDYING', 'Studying'), ('CODING', 'Coding'), ('ASSIGNMENT', 'Assignment'), ('ONLINE_LEARNING', 'Online Learning'), ('GAMES', 'Games'), ('OTHER', 'Other')], default='', max_length=30),
        ),
        migrations.CreateModel(
            name='FocusCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('IDLE_CHECK', 'Idle / Distraction Check'), ('RETURN', 'Return From Away'), ('REFRESH', 'Productive Refresh')], default='IDLE_CHECK', max_length=20)),
                ('state', models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('AWAY', 'Away'), ('SKIPPED', 'Skipped')], default='', max_length=20)),
                ('goal', models.CharField(blank=True, choices=[('STUDYING', 'Studying'), ('CODING', 'Coding'), ('ASSIGNMENT', 'Assignment'), ('ONLINE_LEARNING', 'Online Learning'), ('GAMES', 'Games'), ('OTHER', 'Other')], default='', max_length=30)),
                ('away_secs', models.IntegerField(default=0)),
                ('productive_secs', models.IntegerField(default=0)),
                ('reason', models.CharField(blank=True, default='', max_length=20)),
                ('episode_key', models.CharField(blank=True, default='', max_length=80)),
                ('response_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='focus_sessions.focussession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'kind', 'created_at'], name='focus_sessi_user_id_6e36df_idx')],
            },
        ),
    ]
